{{- if .Values.env.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm-store
  target:
    name: {{ include "app.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range $key, $value := .Values.env.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $value }}
        metadataPolicy: None
    {{- end }}
{{- end }}
